# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0ba53d1343fcc31902209da1105886d35f09dfb23355ddd42c3fcdb9f67e7e19c411c8163cbcd57503dc7c58fdffaab87fc01404fda98d0953462073d9001b2

test:
  secret_key_base: aa0ad3f7e8565906da4a67f4ba66a0507bd94b49749799c87bf71beb9edd55fd62168931e135f33e0e3184248072743048d85a89301c20e7d6bd02a176c2dfc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  DB_HOST: sd1nttcbqt0ds4j.cxsmtmlheyxb.ap-northeast-1.rds.amazonaws.com
  DB_NAME: SumireApp
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
